### ISSUE TITLE
segmentation tasks

### ISSUE THREAD

**Issue by youngbaldy** [OFA-Sys/ONE-PEACE#14]
when i want to use  one_peace_vision.pt as pretrained model for vision tasks,  i met this error:
 - mmseg - INFO - load checkpoint from local path: /home/ONE-PEACE-main/one_peace_vision.pt
Traceback (most recent call last):
  File "one_peace_vision/seg/train.py", line 243, in <module>
    main()
  File "one_peace_vision/seg/train.py", line 203, in main
    model.init_weights()
  File "/data/OEM/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 116, in init_weights
    m.init_weights()
  File "/home/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/backbones/onepeace.py", line 570, in init_weights
    state_dict = self.resize_abs_pos_embed(model)
  File "/home/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/backbones/onepeace.py", line 467, in resize_abs_pos_embed
    pos_embed_checkpoint = checkpoint['image_adapter.pos_embed']
KeyError: 'image_adapter.pos_embed'

i dont know how to handle this problem...

**Comment by simonJJJ** [comment]
Hi, follow [link](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace_vision/README.md) to extract vision branch model. For example:
```
python convert_to_vision.py /path/to/one-peace.pt /save_path/one-peace-vision.pkl
```
Then use the one-peace-vision.pkl for semantic segmentation.

Note that the one_peace_vision.pth is different from one-peace-vision.pkl in model names.

**Comment by youngbaldy** [comment]
oooook, i will try as u suggested, hope you have a nice day, 3Q~

**Comment by hotohoto** [comment]
> Note that the one_peace_vision.pth is different from one-peace-vision.pkl in model names.

Trying to use the pretrained segmentation model just for inference, I have quetions. 

What is https://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_checkpoints/one_peace_vision.pt for and how can I use this?

Thanks in advance. 🙂
