### ISSUE TITLE
corrupt file

### ISSUE THREAD

**Issue by yan-hao-tian** [OFA-Sys/ONE-PEACE#26]
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main()
  File "train.py", line 232, in main
    train_segmentor(
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmseg/apis/train.py", line 193, in train_segmentor
    runner.load_checkpoint(cfg.load_from)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 339, in load_checkpoint
    return load_checkpoint(
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 302, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/torch/serialization.py", line 779, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

我跑了一下segmentation 训练命令是
```
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=12355 --use_env train.py --launcher pytorch configs/ade20k/mask2former_onepeace_adapter_g_896_40k_ade20k_ss.py --load-from=/data/work_dirs/one-peace-vision.pkl --work-dir /data/work_dirs/one_peace/msdeformattn
```

我的问题是：load-from这个参数对应的就是config里的pretrained吧，这里新加一个参数搞得我有点懵。。我认为是，所以就设成了跟pretrained一样的值。之后运行，就出现了上述的error。corrupt file 一般认为是文件不完整导致的？但这个one-peace-vision.pkl就是从readme给的连接直接下载的。
我运行的下载命令是
```
wget https://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_checkpoints/one-peace-vision.pkl
```

期待贵团队的回复。🙏

**Comment by yan-hao-tian** [comment]
Traceback (most recent call last):
File "train.py", line 243, in
main()
File "train.py", line 232, in main
train_segmentor(
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmseg/apis/train.py", line 193, in train_segmentor
runner.load_checkpoint(cfg.load_from)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 339, in load_checkpoint
return load_checkpoint(
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
checkpoint = _load_checkpoint(filename, map_location, logger)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
return CheckpointLoader.load_checkpoint(filename, map_location, logger)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
return checkpoint_loader(filename, map_location)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 302, in load_from_local
checkpoint = torch.load(filename, map_location=map_location)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/opt/anaconda3/envs/mask2former/lib/python3.8/site-packages/torch/serialization.py", line 779, in _legacy_load
raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

I ran a segmentation training command as follows:

```
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=12355 --use_env train.py --launcher pytorch configs/ade20k/mask2former_onepeace_adapter_g_896_40k_ade20k_ss.py --load-from=/data/work_dirs/one-peace-vision.pkl --work-dir /data/work_dirs/one_peace/msdeformattn
```
My question is: Does the `load-from` parameter correspond to the `pretrained` parameter in the configuration file? I added this parameter and set it to the same value as `pretrained`. After running it, I encountered the aforementioned error. The "corrupt file" error typically indicates an incomplete file, but the `one-peace-vision.pkl` file I downloaded directly from the provided link in the readme. The command I used to download is:
```
wget https://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_checkpoints/one-peace-vision.pkl
```
I'm looking forward to your team's response. 🙏

**Comment by yan-hao-tian** [comment]
maybe OOM.
How much memory does one sample need in one card for semantic segmetnation?

**Comment by simonJJJ** [comment]
Hi @yan-hao-tian, thanks for your interests.

```pretrained``` parameter is for pre-trained **backbone model**, which is for one-peace-vision.pkl.
```load-from``` parameter is for pre-trained **whole segmentation model**, which is for onepeace_seg_cocostuff2ade20k.pth

In your case, you should run:
```bash
python -m torch.distributed.launch --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=12355 --use_env train.py --launcher pytorch configs/ade20k/mask2former_onepeace_adapter_g_896_40k_ade20k_ss.py --work-dir /data/work_dirs/one_peace/msdeformattn --cfg-options model.pretrained=/data/work_dirs/one-peace-vision.pkl
```

**Comment by simonJJJ** [comment]
Also, if you use the 896x896 input resolution, the GPU memory is approximately 56G for one sample in one card. I recommend a lower resolution for fewer GPU memory budget.

For lower-resolution training, you should change other related hyperparameters. Please refer to [link](https://github.com/OFA-Sys/ONE-PEACE/issues/23#issuecomment-1649352449).

**Comment by yan-hao-tian** [comment]
Thanks for the detailed response.
Btw. Have your team run semseg using samples of size 640x640?

**Comment by simonJJJ** [comment]
@yan-hao-tian Yes, we have run semseg of size 640x640 in some early experiments. But we do not have the plan to release these checkpoints.

**Comment by yan-hao-tian** [comment]
Could you please tell me the mIoU of 640x640? 🥺

**Comment by simonJJJ** [comment]
@yan-hao-tian, we have run several early experiments directly on ADE20k (w/o intermediate fine-tuning) of 640x640 under the single-scale test setting. And the mIoU are 59.4, 59.66, 59.77, 60.35.
