### ISSUE TITLE
Semantic Segmentation: test.py missing file <schedule_40k.py>

### ISSUE THREAD

**Issue by Masadda** [OFA-Sys/ONE-PEACE#45]
Hi,

I'm trying to use your semantic segmentation; after following the installation instructions (general + for semantic seg.) when trying to run `test.py` as per the instruction
`python -m torch.distributed.launch --nproc_per_node=8 --nnodes=$NNODES --node_rank=$NODE_RANK --master_addr=$MASTER_ADDR --master_port=12355 --use_env test.py --launcher pytorch configs/ade20k/mask2former_onepeace_adapter_g_896_40k_ade20k_ss.py /path/to/onepeace_seg_cocostuff2ade20k.pth --eval mIoU`
the following error occurs:

>   warnings.warn(
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File ".../ONE-PEACE/one_peace_vision/seg/test.py", line 321, in <module>
    main()
  File ".../ONE-PEACE/one_peace_vision/seg/test.py", line 133, in main
    cfg = mmcv.Config.fromfile(args.config)
  File "<ENV_PATH>/lib/python3.9/site-packages/mmcv/utils/config.py", line 337, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "<ENV_PATH>/lib/python3.9/site-packages/mmcv/utils/config.py", line 251, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "<ENV_PATH>/lib/python3.9/site-packages/mmcv/utils/config.py", line 182, in _file2dict
    check_file_exist(filename)
  File "<ENV_PATH>/lib/python3.9/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file ".../ONE-PEACE/one_peace_vision/seg/configs/_base_/schedules/schedule_40k.py" does not exist
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1993643) of binary: <ENV_PATH>/bin/python
Traceback (most recent call last):
  File "<ENV_PATH>/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<ENV_PATH>/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "<ENV_PATH>/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
test.py FAILED
Failures:
  <NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
  time      : 2023-12-21_00:30:51
  host      : #########
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1993643)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

There seems to be a file missing from the repository. Can someone please provide me with either the required file or how to otherwise prevent the error?

**Comment by Masadda** [comment]
Still looking for a solution. Any help would be greatly appreciated.

**Comment by Masadda** [comment]
Found the solution. 
Simply use the schedule file from the original mmsegmentation repository and put it in the corresponding filepath.
Still, if this code / readme depends on it maybe add it to this repository as well.
